#!/usr/bin/env python3
"""Generate ARTICLES.md — the fully expanded view of README's Articles tree.

GitHub strips scripts from Markdown, so "Expand all" cannot toggle <details> in
place. Instead README links to ARTICLES.md (same tree, every <details> open) and
"Collapse all" re-renders README, whose tree is collapsed by default.

Usage: python3 wiki/scripts/sync-articles-view.py
"""

import re
from pathlib import Path

VAULT_ROOT = Path(__file__).resolve().parent.parent.parent
README_FILE = VAULT_ROOT / "README.md"
ARTICLES_FILE = VAULT_ROOT / "ARTICLES.md"

EXPAND_BTN = "asset/articles-expand-all-2026-10-10.svg"
COLLAPSE_BTN = "asset/articles-collapse-all-2026-10-10.svg"
SEARCH_BTN = "asset/articles-search-2026-10-10.svg"
SEARCH_URL = "https://huqianghui.github.io/mindforge/articles/"
# Collapse must force GitHub to re-render the README. A link to the current URL only scrolls, so it
# points at tree/…/README.md, which GitHub redirects to blob/…/README.md: the address you land on
# never equals the link, so every click re-renders with all <details> closed.
COLLAPSE_URL = "https://github.com/huqianghui/mindforge/tree/main/README.md"
NAV = (f'<p><a href="ARTICLES.md#articles"><img src="{EXPAND_BTN}" alt="Expand all" height="34"></a>'
       f'&nbsp;<a href="{COLLAPSE_URL}"><img src="{COLLAPSE_BTN}" alt="Collapse all" height="34"></a>'
       f'&nbsp;<a href="{SEARCH_URL}"><img src="{SEARCH_BTN}" alt="Search" height="34"></a></p>')


def articles_body(readme: str) -> str:
    start = readme.index("## Articles\n") + len("## Articles\n")
    end = readme.index("\n---\n", start)
    return readme[start:end]


def ensure_readme_nav(readme: str) -> str:
    """Put the button row right under the Articles heading (idempotent)."""
    body = articles_body(readme)
    clean = "\n".join(l for l in body.split("\n") if "articles-expand-all" not in l).lstrip("\n")
    return readme.replace("## Articles\n" + body, "## Articles\n\n" + NAV + "\n\n" + clean, 1)


def sync_articles_view() -> None:
    readme = README_FILE.read_text(encoding="utf-8")
    new_readme = ensure_readme_nav(readme)
    if new_readme != readme:
        README_FILE.write_text(new_readme, encoding="utf-8")
    body = articles_body(new_readme)
    body = "\n".join(l for l in body.split("\n") if "articles-expand-all" not in l)
    body = re.sub(r"<!--.*?-->\n?", "", body, flags=re.DOTALL)
    body = body.replace("<details>", "<details open>").strip("\n")
    out = (
        "# Mindforge\n\n"
        "<!-- Generated by wiki/scripts/sync-articles-view.py from README.md — do not edit by hand. -->\n\n"
        "## Articles\n\n"
        f"{NAV}\n\n"
        f"{body}\n\n"
        "---\n\n"
        f"[← Back to README]({COLLAPSE_URL})\n"
    )
    if not ARTICLES_FILE.exists() or ARTICLES_FILE.read_text(encoding="utf-8") != out:
        ARTICLES_FILE.write_text(out, encoding="utf-8")
        print(f"Updated {ARTICLES_FILE}")


if __name__ == "__main__":
    sync_articles_view()
