#!/usr/bin/env python3
"""Generate ARTICLES.md — the fully expanded view of README's Articles tree.

GitHub strips scripts from Markdown, so "Expand all" cannot toggle <details> in
place. Instead README links to ARTICLES.md (same tree, every <details> open); README
itself stays collapsed by default.

Usage: python3 wiki/scripts/sync-articles-view.py
"""

import re
from pathlib import Path

VAULT_ROOT = Path(__file__).resolve().parent.parent.parent
README_FILE = VAULT_ROOT / "README.md"
ARTICLES_FILE = VAULT_ROOT / "ARTICLES.md"

EXPAND_BTN = "asset/articles-expand-all-2026-10-10.svg"
SEARCH_BTN = "asset/articles-search-2026-10-10.svg"
SEARCH_URL = "https://huqianghui.github.io/mindforge/articles/"
SEARCH_LINK = f'<a href="{SEARCH_URL}"><img src="{SEARCH_BTN}" alt="Search" height="34"></a>'
README_NAV = (f'<p><a href="ARTICLES.md#articles"><img src="{EXPAND_BTN}" alt="Expand all" height="34"></a>'
              f'&nbsp;{SEARCH_LINK}</p>')
ARTICLES_NAV = f'<p>{SEARCH_LINK}</p>'
NAV_MARK = "articles-search-2026"  # every nav row contains the Search button


def articles_body(readme: str) -> str:
    start = readme.index("## Articles\n") + len("## Articles\n")
    end = readme.index("\n---\n", start)
    return readme[start:end]


def ensure_readme_nav(readme: str) -> str:
    """Put the button row right under the Articles heading (idempotent)."""
    body = articles_body(readme)
    clean = "\n".join(l for l in body.split("\n") if NAV_MARK not in l).lstrip("\n")
    return readme.replace("## Articles\n" + body, "## Articles\n\n" + README_NAV + "\n\n" + clean, 1)


def sync_articles_view() -> None:
    readme = README_FILE.read_text(encoding="utf-8")
    new_readme = ensure_readme_nav(readme)
    if new_readme != readme:
        README_FILE.write_text(new_readme, encoding="utf-8")
    body = articles_body(new_readme)
    body = "\n".join(l for l in body.split("\n") if NAV_MARK not in l)
    body = re.sub(r"<!--.*?-->\n?", "", body, flags=re.DOTALL)
    body = body.replace("<details>", "<details open>").strip("\n")
    out = (
        "# Mindforge\n\n"
        "<!-- Generated by wiki/scripts/sync-articles-view.py from README.md — do not edit by hand. -->\n\n"
        "## Articles\n\n"
        f"{ARTICLES_NAV}\n\n"
        f"{body}\n\n"
        "---\n\n"
        "[← Back to README](README.md)\n"
    )
    if not ARTICLES_FILE.exists() or ARTICLES_FILE.read_text(encoding="utf-8") != out:
        ARTICLES_FILE.write_text(out, encoding="utf-8")
        print(f"Updated {ARTICLES_FILE}")


if __name__ == "__main__":
    sync_articles_view()
